# Generated by Django 3.0.1 on 2020-03-31 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_table',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=100)),
                ('job_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('num_skills', models.IntegerField(blank=True)),
                ('lang_score', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=15, null=True), size=None)),
                ('job_exp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
                ('company_rating', models.FloatField(max_length=2)),
                ('job_age', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='language_table',
            fields=[
                ('lang_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('experience', models.FloatField(max_length=4)),
                ('forks', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('recent_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='recom_table',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=100)),
                ('job_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('job_exp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
                ('score', models.FloatField(max_length=4)),
                ('match', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='repos_table',
            fields=[
                ('repos_name', models.CharField(max_length=100)),
                ('repos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('repos_owner_id', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('create_date', models.CharField(max_length=10)),
                ('update_date', models.CharField(max_length=10)),
                ('forks', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('open_issues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('repos', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
