# Generated by Django 3.0.1 on 2020-03-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_recom_table_recom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recom_table',
            name='job_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recom_table',
            name='recom_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
