# Generated by Django 3.0.1 on 2020-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200331_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='recom_table',
            name='link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
