# Generated by Django 3.0.1 on 2020-03-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_recom_table_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='analysis_pic',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_pics'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pics'),
        ),
    ]
