# Generated by Django 3.0.1 on 2020-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_userinfo_exp_analysis_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_table',
            name='num_repos',
            field=models.IntegerField(default=0),
        ),
    ]
