# Generated by Django 3.0.1 on 2020-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_language_table_num_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recom_table',
            name='match_score',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
    ]
